# all resources: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-template-resource-type-ref.html

# !!! when adjusting some parameters here, update the documentation (web/src/docs/documentation.md)
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend and Frontend setup for APIForge. 

Globals:
  Function:
    Runtime: java21
    Environment:
      # global environment variables for all lambdas, must be set in GlobalConfig.java in common-utils
      Variables:
        ENV: !Ref Environment
        AWS_REGION: !Ref AwsRegion
        LOG_LEVEL: "INFO"

Parameters:
  Environment:
    Type: String
    AllowedValues: [local, stg, prod]
  AwsRegion:
    Type: String
  LambdaMemory:
    Type: Number
  MaxDeploymentsPerUser:
    Type: Number
  # those should not be set manually by the samconfig.toml but use the default value
  DeploymentsMetadataTableName:
    Type: String
    Default: "deployments-metadata"
  UserCodeBucketPrefix:
    Type: String
    Default: "code-uploads"
  EcrRepositoryName:
    Type: String
    Default: "user-apps"

Conditions:
  isNotLocal: !Not [ !Equals [ !Ref Environment, local ] ]

Resources:
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nested/auth.yml

  FrontendStack:
    Type: AWS::Serverless::Application
    Condition: isNotLocal
    Properties:
      Location: ./nested/frontend.yml

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      # as we set the gateway as proxy, it does not add any CORS headers, so we set them in Quarkus (application.properties) and let API Gateway forward them
      Cors:
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD'"
        AllowHeaders: "'Accept,Authorization,Content-Type,X-Requested-With'"
        AllowOrigin: !If [ isNotLocal, !Sub "https://${FrontendStack.Outputs.CloudFrontDistribution}", "'*'" ]
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn

  BackendAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Fat JAR with maven shade plugin
      CodeUri: ../lambda/backend-api-lambda/target/function.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Timeout: 15
      Architectures:
        - arm64
      MemorySize: !Ref LambdaMemory
      Events:
        # set health check endpoint unauthenticated
        HealthEvent:
          Type: Api
          Properties:
            Path: /api/v1/health # renaming this endpoint requires renaming in backend api health resource
            Method: GET
            RestApiId: !Ref APIGateway
            Auth:
              Authorizer: NONE
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          # for CORS header in lambda responses, set by Quarkus in application.properties
          ALLOWED_ORIGIN: !If [ isNotLocal, !Sub "https://${FrontendStack.Outputs.CloudFrontDistribution}", "http://localhost:8080" ]
          COGNITO_USER_POOL_ID: !GetAtt AuthStack.Outputs.UserPoolId
          DEPLOYMENTS_METADATA_TABLE: !Ref DeploymentsMetadataTable
          MAX_DEPLOYMENTS_PER_USER: !Ref MaxDeploymentsPerUser 
          BUILD_QUEUE_URL: !Ref BuildJobQueue 
          USER_CODE_BUCKET: !Ref UserCodeBucket
          USER_CODE_BUCKET_PREFIX: !Ref UserCodeBucketPrefix
      Policies:
        # generate presigned S3 URLs
        - S3ReadPolicy:
            BucketName: !Ref UserCodeBucket
        - S3WritePolicy:
            BucketName: !Ref UserCodeBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DeploymentsMetadataTable
      # TODO sqs etc

  DeploymentsMetadataTable:
  # not AWS::Serverless:SimpleTable for secondary key
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DeploymentsMetadataTableName
      BillingMode: PAY_PER_REQUEST 
      # renaming of userId or deploymentId requires renaming in backend api lambda data model
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deploymentId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH # Partition Key
        - AttributeName: deploymentId
          KeyType: RANGE # Sort Key
      SSESpecification:
        SSEEnabled: true

  UserCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      # block any public access, only presigned URLs generated from backend api lambda
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - !If [ isNotLocal, !Sub "https://${FrontendStack.Outputs.CloudFrontDistribution}", "http://localhost:8080" ]
            MaxAge: 3000

  BuildJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      # no duplicates
      FifoQueue: true
      ContentBasedDeduplication: true
      # if SQS lambda crashes
      VisibilityTimeout: 90 # lambda timeout x 6 retries
      MessageRetentionPeriod: 86400

  SQSDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/sqs-dispatcher-lambda/target/function.zip
      Handler: com.hosting.dispatcher.handler.SqsDispatcherHandler::handleRequest
      Timeout: 30 # if CodeBuild startBuild takes very long
      MemorySize: 128 # only dispatching, not much memory needed
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BuildJobQueue.Arn
            BatchSize: 1 # one deployment per instance
      Environment:
        Variables:
          CODEBUILD_PROJECT_NAME: !Ref CodeBuild
          USER_CODE_BUCKET: !Ref UserCodeBucket
          USER_CODE_BUCKET_PREFIX: !Ref UserCodeBucketPrefix # for generating presigned URLs for user code uploads
          ECR_REPOSITORY_URI: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepositoryName}"
      #Policies:
        # TODO

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildDockerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # write logs
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              # read code from S3
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: !Sub "arn:aws:s3:::${UserCodeBucket}/*"
              # ECR login & push
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: !GetAtt EcrRepository.Arn

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        PrivilegedMode: true # required für Docker builds          
      Source:
        Type: S3
        Location: !Sub "${UserCodeBucket}/${UserCodeBucketPrefix}"
      # LogsConfig:
      #   CloudWatchLogs:
      #     Status: ENABLED
      #     GroupName: !Ref CodeBuildLogGroup

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepositoryName
      LifecyclePolicy:
        # first rule would only apply if updated image with same tag
        # --> old gets untagged
        # (only if user can update a deployment)
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete ghost images without tag after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep only 3 images per user prefix",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["user-"],
                  "countType": "imageCountMoreThan",
                  "countNumber": ${MaxDeploymentsPerUser}
                },
                "action": { "type": "expire" }
              }
            ]
          }

  FunctionDeployer: 
  # triggered by custom EventBridge event after codebuild uploaded to ECR to deploy user's lambda with the image
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/function-deployer-lambda/target/function.zip
      Handler: com.hosting.deployer.handler.FunctionDeployerHandler::handleRequest
      Timeout: 30 # if deployment takes very long
      MemorySize: 128 # only creation, not much memory needed
      Events:
        DeploymentEvent:
          Type: EventBridgeRule
          Properties:
            # must match the event in EventBridgeRepository.java
            Pattern:
              source:
                - "com.hosting.dispatcher"
              detail-type:
                - "CodeBuildJobStarted"
              detail:
                status:
                  - "SUCCESS"
      Environment:
        Variables:
            ECR_REPOSITORY_URI: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepositoryName}"
      #Policies:
        # TODO

  BackendAPILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # name must be same as Lambda function name to control default log created by lambda
      LogGroupName: !Sub "/aws/lambda/${BackendAPIFunction}" 
      RetentionInDays: 7

  # CodeBuildLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub "/aws/codebuild/${CodeBuild}" 
  #     RetentionInDays: 7

  SQSDispatcherLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # name must be same as Lambda function name to control default log created by lambda
      LogGroupName: !Sub "/aws/lambda/${SQSDispatcherFunction}" 
      RetentionInDays: 7

  FunctionDeployerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # name must be same as Lambda function name to control default log created by lambda
      LogGroupName: !Sub "/aws/lambda/${FunctionDeployer}" 
      RetentionInDays: 7

# changing the output names requires renaming in connect-frontend.sh
Outputs:
  Region:
    Description: "AWS Region of the stack"
    Value: !Ref "AWS::Region"

  ApiId:
    Description: "API ID"
    Value: !Ref APIGateway
  
  UserPoolId:
    Description: "UserPool ID"
    Value: !GetAtt AuthStack.Outputs.UserPoolId
  
  UserPoolClientId:
    Description: "UserPoolClient ID"
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId