# all resources: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-template-resource-type-ref.html

# !!! when adjusting some parameters here, update the documentation (web/src/docs/documentation.md)
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend and Frontend setup for APIForge. 

Globals:
  Function:
    Runtime: java25

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, stg, prod]
  AwsRegion:
    Type: String
  LambdaMemory:
    Type: Number
  MaxDeploymentsPerUser:
    Type: Number

Conditions:
  isNotLocal: !Not [ !Equals [ !Ref Environment, local ] ]

Resources:
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nested/auth.yml

  FrontendStack:
    Type: AWS::Serverless::Application
    Condition: isNotLocal
    Properties:
      Location: ./nested/frontend.yml

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'ANY'" # specified in Quarkus
        AllowOrigin: !If [ isNotLocal, !Sub "https://${FrontendStack.Outputs.CloudFrontDistribution}", "'*'" ]
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn

  CoreBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Fat JAR with maven shade plugin
      CodeUri: ../lambda/core-backend-lambda/target/function.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Timeout: 15
      Architectures:
        - arm64
      MemorySize: !Ref LambdaMemory
      Events:
        # set health check endpoint unauthenticated
        HealthEvent:
          Type: Api
          Properties:
            Path: /api/v1/health
            Method: GET
            RestApiId: !Ref APIGateway
            Auth:
              Authorizer: NONE
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          ENV: !Ref Environment
          AWS_REGION: !Ref AwsRegion # that deployment region and lambda region are the same
          MAX_DEPLOYMENTS_PER_USER: !Ref MaxDeploymentsPerUser # for build orchestrator lambda to check before starting a build
          BUILD_QUEUE_URL: !Ref BuildJobQueue # for sending build requests from core backend to build orchestrator lambda
          USER_CODE_BUCKET: !Ref UserCodeBucket # for generating presigned URLs for user code uploads
      Policies:
        # generate presigned S3 URLs
        - S3ReadPolicy:
            BucketName: !Ref UserCodeBucket
        - S3WritePolicy:
            BucketName: !Ref UserCodeBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DeploymentsMetadataTable

  DeploymentsMetadataTable:
  # not AWS::Serverless:SimpleTable for secondary key
    Type: AWS::DynamoDB::Table
    Properties:
      Name: "deployments-metadata"
      BillingMode: PAY_PER_REQUEST 
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deploymentId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH # Partition Key
        - AttributeName: deploymentId
          KeyType: RANGE # Sort Key
      SSESpecification:
        SSEEnabled: true

  UserCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      # block any public access, only presigned URLs generated from core backend lambda
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  BuildJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      # no duplicates
      FifoQueue: true
      ContentBasedDeduplication: true
      # if SQS lambda crashes
      VisibilityTimeout: 90 # lambda timeout x 6 retries

  BuildOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/build-orchestrator-lambda/target/function.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BuildJobQueue.Arn
            BatchSize: 1 # one deployment per instance

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildDockerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # write logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              # read code from S3
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: !Sub "arn:aws:s3:::${UserCodeBucket}/*"
              # ECR login & push
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: !GetAtt EcrRepository.Arn
              # 4. user Lambda update (end of deployment, see buildspec.yml)
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                Resource: "*" # TODO more specific for user lambdas only

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "user-image-builds-${Environment}"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
        PrivilegedMode: true # required für Docker builds
        EnvironmentVariables:
          # set here so that it is fixed, all others in buildspec.yml will be set by Java SDK
          - Name: REPOSITORY_URI
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/user-apps"
      Source:
        Type: S3
        Location: !Sub "${UserCodeBucket}/code-uploads/" # TODO
      # LogConfig: # TODO, needed for frontend logs

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      # name must be same in CodeBuild REPOSITORY_URI
      RepositoryName: "user-apps"
      LifecyclePolicy:
        # first rule would only apply if updated image with same tag
        # --> old gets untagged
        # (only if user can update a deployment)
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete ghost images without tag after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Keep only 3 images per user prefix",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["user-"],
                  "countType": "imageCountMoreThan",
                  "countNumber": ${MaxDeploymentsPerUser}
                },
                "action": { "type": "expire" }
              }
            ]
          }

  # TODO cloudwatch with retention period to keep logs small

# changing the output names requires renaming in connect-frontend.sh
Outputs:
  Region:
    Description: "AWS Region of the stack"
    Value: !Ref "AWS::Region"

  ApiId:
    Description: "API ID"
    Value: !Ref APIGateway
  
  UserPoolId:
    Description: "UserPool ID"
    Value: !GetAtt AuthStack.Outputs.UserPoolId
  
  UserPoolClientId:
    Description: "UserPoolClient ID"
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId

  SQSQueueUrl:
    Description: "Auto-generated SQS Queue URL"
    Value: !Ref BuildJobQueue

  EcrRepositoryUri:
    Description: "ECR Repository URI"
    Value: !GetAtt EcrRepository.RepositoryUri

  WebBucketName:
    Condition: isNotLocal
    Description: "The S3 bucket for web assets"
    Value: !GetAtt FrontendStack.Outputs.WebBucketName