name: Setup Java and Maven
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: lambda/pom.xml
    - name: Make wrapper executable
      run: chmod +x lambda/mvnw
      shell: bash