# Enable CORS support separately from API Gateway, as we use it in proxy mode and API Gateway will forward the CORS headers set by Quarkus to the client.
quarkus.http.cors=true
# Env variable set in template.yml, allows requests from frontend deployed on CloudFront and localhost during development
quarkus.http.cors.origins=${ALLOWED_ORIGIN}
# Allow the methods and headers needed for API Gateway integration
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
