# see https://docs.github.com/de/actions/tutorials/build-and-test-code/java-with-maven
name: Backend CI checks

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string

jobs:
  ci-checks:
    name: CI Checks – ${{ inputs.module-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-maven
      - uses: ./.github/actions/setup-just

      - name: Create Build Artifact
        run: just lambda install ${{ inputs.module-name }}

      - name: Static Code Analysis
        run: |
          just ${{ inputs.module-name }} lint
          just ${{ inputs.module-name }} code-analysis

      - name: Run Unit Tests
        run: just ${{ inputs.module-name }} unit-test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apiforge-${{ inputs.module-name }}-artifact
          path: lambda/${{ inputs.module-name }}/target/function.zip # for lambda packaging, must match name in template.yml
          retention-days: 1

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.module-name }}
          path: lambda/${{ inputs.module-name }}/target/surefire-reports/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.module-name }}
          path: lambda/${{ inputs.module-name }}/target/site/jacoco/