name: CI Orchestrator
on:    
  pull_request:
    branches: [main]

jobs:
  detect-code-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.filter.outputs.frontend }}
      sqs-dispatcher-changed: ${{ steps.filter.outputs.sqs-dispatcher }}
      function-deployer-changed: ${{ steps.filter.outputs.function-deployer }}
      common-utils-changed: ${{ steps.filter.outputs.common-utils }}
      backend-api-changed: ${{ steps.filter.outputs.backend-api }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            global:
              - '.github/workflows/**'
              - '.github/actions/**'
              - 'lambda/pom.xml'
              - 'justfile'
            frontend:
              - 'web/**'
            common-utils:
              - 'lambda/common-utils/**'
            sqs-dispatcher:
              - 'lambda/sqs-dispatcher-lambda/**'
            backend-api:
              - 'lambda/backend-api-lambda/**'
            function-deployer:
              - 'lambda/function-deployer-lambda/**'

  run-common-utils-ci-checks:
    needs: detect-code-changes
    if: |
      needs.detect-code-changes.outputs.common-utils-changed == 'true' ||
      needs.detect-code-changes.outputs.global-changed == 'true'
    uses: ./.github/workflows/backend-ci.yml
    with:
      module-name: common-utils

  run-sqs-dispatcher-ci-checks:
    needs: detect-code-changes
    if: |
      needs.detect-code-changes.outputs.sqs-dispatcher-changed == 'true' ||
      needs.detect-code-changes.outputs.common-utils-changed == 'true' ||
      needs.detect-code-changes.outputs.global-changed == 'true'
    uses: ./.github/workflows/backend-ci.yml
    with:
      module-name: sqs-dispatcher-lambda

  run-function-deployer-ci-checks:
    needs: detect-code-changes
    if: |
      needs.detect-code-changes.outputs.function-deployer-changed == 'true' ||
      needs.detect-code-changes.outputs.common-utils-changed == 'true' ||
      needs.detect-code-changes.outputs.global-changed == 'true'
    uses: ./.github/workflows/backend-ci.yml
    with:
      module-name: function-deployer-lambda

  run-backend-api-ci-checks:
    needs: detect-code-changes
    if: |
      needs.detect-code-changes.outputs.backend-api-changed == 'true' ||
      needs.detect-code-changes.outputs.common-utils-changed == 'true' ||
      needs.detect-code-changes.outputs.global-changed == 'true'
    uses: ./.github/workflows/backend-ci.yml
    with:
      module-name: backend-api-lambda

  run-frontend-ci-checks:
    needs: detect-code-changes
    if: |
      needs.detect-code-changes.outputs.frontend-changed == 'true' ||
      needs.detect-code-changes.outputs.global-changed == 'true'
    uses: ./.github/workflows/frontend-ci.yml
    with:
      module-name: web