name: Frontend CI checks

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string

jobs:
  build-and-check:
    name: Build & Check – ${{ inputs.module-name }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read  

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-just

      - uses: ./.github/actions/setup-node
        with:
          module-name: ${{ inputs.module-name }}

      - name: Configure AWS Staging Credentials (OIDC) for Code Artifacts
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::071308038858:role/GitHubActionsDeploymentRole # role name should match the one in bootstrap/template.yml
          aws-region: eu-central-1

      - name: Install dependencies
        run: just ${{ inputs.module-name }} install

      - name: Lint
        run: just ${{ inputs.module-name }} lint

      - name: Type Check
        run: just ${{ inputs.module-name }} type-check

      - name: Build
        run: just ${{ inputs.module-name }} build

      - name: Unit Tests
        run: just ${{ inputs.module-name }} test-unit
